# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e811bdf28b5c1dc53e643da101af58873e27f52795b97de4a5a12cfe9348c9efc190bf782fa78409bb067c0f6bd5489a01fb432d79dd3cabfa1581d72bd8656

test:
  secret_key_base: c1be3c2625b4ec184cdb2eba8fc8b32d657f2c98f47fb8ad8d41fafd8a645c7091a6a8593e472d173e27204e684ded80ce1902b803c33f9a2cc13ecc2b5eb0f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
